# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_ccpp_manzanas_rutas_secciones_viviendau_viviendaurbana_zonacensal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aeus',
            table='sde.TB_AEUS',
        ),
    ]
